"""added relationship

Revision ID: 6b167db1d69c
Revises: a8107128707a
Create Date: 2025-07-22 18:17:47.308983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b167db1d69c'
down_revision: Union[str, Sequence[str], None] = 'a8107128707a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('validation_token_user_id_fkey'), 'validation_token', type_='foreignkey')
    op.create_foreign_key(None, 'validation_token', 'pending_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_token', type_='foreignkey')
    op.create_foreign_key(op.f('validation_token_user_id_fkey'), 'validation_token', 'pending_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
