"""updated 2 the reset password table

Revision ID: cf7de2727b6d
Revises: e4a7ae7e08a7
Create Date: 2025-07-23 13:48:52.309693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7de2727b6d'
down_revision: Union[str, Sequence[str], None] = 'e4a7ae7e08a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
